#! /usr/bin/env ruby
require 'git_command'

command :clone do |repo_name|
	`git clone https://github.com/#{ repo_name }`
end

command :create do |user_name, repo_name|
	system "curl -u '#{ user_name }' https://api.github.com/user/repos -d '{\"name\":\"#{ repo_name }\"}'"
	system "git remote add origin git@github.com:#{ user_name }/#{ repo_name }.git"
	system "git push -u origin master"
end
