#! /usr/bin/env ruby

def main
	issue_number = ARGV[0]
	branch = "CNVS-#{issue_number}"

	branches = `git branch`

	if branches.include? branch
		`git checkout #{branch}`
	else
		`git checkout -b #{branch}`
	end
end

main
