#! /usr/bin/env ruby
require 'thor'

class Hub < Thor
  desc 'clone', 'clones a repo from github'
  def clone(id)
    system "git clone git@github.com:#{ id }.git"
  end

  desc 'create', 'creates a repo on github'
  def create(user_name, repo_name)
    system "curl -u '#{ user_name }' https://api.github.com/user/repos -d '{\"name\":\"#{ repo_name }\"}'"
    system "git remote add origin git@github.com:#{ user_name }/#{ repo_name }.git"
    system "git push -u origin master"
  end
end

Hub.start(ARGV)
